# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: objective-c
xcode_project: _Pods.xcodeproj
xcode_scheme: TLCustomMask_Tests
xcode_sdk: iphonesimulator10.1

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
 - xcodebuild clean build test -project _Pods.xcodeproj -scheme TLCustomMask_Tests -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
