# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.1
language: objective-c
xcode_workspace: Example/TLCustomMask.xcworkspace
xcode_scheme: TLCustomMask-Example
xcode_sdk: iphonesimulator10.1
